### ISSUE TITLE
ardupilot-manager: can't get available firmwares because of SSL error

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#1123]
Tracking for [this problem in our forums](https://discuss.bluerobotics.com/t/ardusub-firmware-update-no-data-available/12589) (relevant log at the end of this issue).

The problem is probably related to [this line](https://github.com/bluerobotics/BlueOS-docker/blob/5edf44be291608aab29a590f115f40c79b181043/core/services/ardupilot_manager/firmware/FirmwareDownload.py#L28).

The comment [in this answer](https://stackoverflow.com/a/52172355/4465365) probably solves our problem.

```bash
2022-08-12 22:58:51.715 | ERROR    | commonwealth.utils.apis:custom_route_handler:34 - Unhandled service exception.
2022-08-12 22:58:51.716 | ERROR    | commonwealth.utils.apis:custom_route_handler:35 - <urlopen error [SSL] unknown error (_ssl.c:1129)>
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
    │ │       │   │             │   │         │   │     └ {'Host': 'firmware.ardupilot.org', 'User-Agent': 'Python-urllib/3.9', 'Connection': 'close'}
    │ │       │   │             │   │         │   └ <property object at 0xb5affac8>
    │ │       │   │             │   │         └ <urllib.request.Request object at 0xb4de2af0>
    │ │       │   │             │   └ '/manifest.json.gz'
    │ │       │   │             └ <urllib.request.Request object at 0xb4de2af0>
    │ │       │   └ <function Request.get_method at 0xb5b0a9b8>
    │ │       └ <urllib.request.Request object at 0xb4de2af0>
    │ └ <function HTTPConnection.request at 0xb5e3a7c0>
    └ <http.client.HTTPSConnection object at 0xb4de21c0>
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
    │    │             │       │    │     │        └ False
    │    │             │       │    │     └ {'Host': 'firmware.ardupilot.org', 'User-Agent': 'Python-urllib/3.9', 'Connection': 'close'}
    │    │             │       │    └ None
    │    │             │       └ '/manifest.json.gz'
    │    │             └ 'GET'
    │    └ <function HTTPConnection._send_request at 0xb5e3a808>
    └ <http.client.HTTPSConnection object at 0xb4de21c0>
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
    │    │          │                    └ False
    │    │          └ None
    │    └ <function HTTPConnection.endheaders at 0xb5e3a778>
    └ <http.client.HTTPSConnection object at 0xb4de21c0>
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    │    │            │                            └ False
    │    │            └ None
    │    └ <function HTTPConnection._send_output at 0xb5e3a580>
    └ <http.client.HTTPSConnection object at 0xb4de21c0>
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
    │    │    └ b'GET /manifest.json.gz HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: firmware.ardupilot.org\r\nUser-Agent: Python-urllib/3....
    │    └ <function HTTPConnection.send at 0xb5e3a4a8>
    └ <http.client.HTTPSConnection object at 0xb4de21c0>
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
    │    └ <function HTTPSConnection.connect at 0xb5e3a8e0>
    └ <http.client.HTTPSConnection object at 0xb4de21c0>
  File "/usr/local/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
    │    │      │    │        │           │    └ None
    │    │      │    │        │           └ <http.client.HTTPSConnection object at 0xb4de21c0>
    │    │      │    │        └ <function SSLContext.wrap_socket at 0xb65494a8>
    │    │      │    └ <ssl.SSLContext object at 0xb5624ec8>
    │    │      └ <http.client.HTTPSConnection object at 0xb4de21c0>
    │    └ None
    └ <http.client.HTTPSConnection object at 0xb4de21c0>
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0xb653ff28>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0xb5624ec8>
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0xb654bbf8>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL] unknown error (_ssl.c:1129)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0xb4de2b68>
                     └ <function GenericErrorHandlingRoute.get_route_handler.<locals>.custom_route_handler at 0xb56e2fa0>
> File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/utils/apis.py", line 29, in custom_route_handler
    return await original_route_handler(request)
                 │                      └ <starlette.requests.Request object at 0xb4de2b68>
                 └ <function get_request_handler.<locals>.app at 0xb56e2e38>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0xb5e82ec8>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
                 │                 │         │       └ {'vehicle': <Vehicle.Sub: 'Sub'>}
                 │                 │         └ <function get_available_firmwares at 0xb56e2df0>
                 │                 └ <fastapi.dependencies.models.Dependant object at 0xb56d3388>
                 └ <function run_in_threadpool at 0xb6042388>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
                 │    │                     │      └ (functools.partial(<function get_available_firmwares at 0xb56e2df0>, vehicle=<Vehicle.Sub: 'Sub'>),)
                 │    │                     └ <built-in method run of Context object at 0xb4dc5908>
                 │    └ <function BaseEventLoop.run_in_executor at 0xb640e148>
                 └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "/home/pi/services/ardupilot_manager/main.py", line 83, in get_available_firmwares
    return autopilot.get_available_firmwares(vehicle, autopilot.current_board.platform)
           │         │                       │        │         └ <property object at 0xb56debe0>
           │         │                       │        └ <ArduPilotManager.ArduPilotManager object at 0xb56d8550>
           │         │                       └ <Vehicle.Sub: 'Sub'>
           │         └ <function ArduPilotManager.get_available_firmwares at 0xb56e2268>
           └ <ArduPilotManager.ArduPilotManager object at 0xb56d8550>

  File "/home/pi/services/ardupilot_manager/ArduPilotManager.py", line 434, in get_available_firmwares
    return self.firmware_manager.get_available_firmwares(vehicle, platform)
           │    │                │                       │        └ <Platform.Navigator: 'navigator'>
           │    │                │                       └ <Vehicle.Sub: 'Sub'>
           │    │                └ <function FirmwareManager.get_available_firmwares at 0xb577ad60>
           │    └ <firmware.FirmwareManagement.FirmwareManager object at 0xb56d8568>
           └ <ArduPilotManager.ArduPilotManager object at 0xb56d8550>

  File "/home/pi/services/ardupilot_manager/firmware/FirmwareManagement.py", line 63, in get_available_firmwares
    versions = self.firmware_download.get_available_versions(vehicle, platform)
               │    │                 │                      │        └ <Platform.Navigator: 'navigator'>
               │    │                 │                      └ <Vehicle.Sub: 'Sub'>
               │    │                 └ <function FirmwareDownloader.get_available_versions at 0xb5977928>
               │    └ <firmware.FirmwareDownload.FirmwareDownloader object at 0xb56d8658>
               └ <firmware.FirmwareManagement.FirmwareManager object at 0xb56d8568>

  File "/home/pi/services/ardupilot_manager/firmware/FirmwareDownload.py", line 146, in get_available_versions
    if not self._manifest_is_valid():
           │    └ <function FirmwareDownloader._manifest_is_valid at 0xb5977850>
           └ <firmware.FirmwareDownload.FirmwareDownloader object at 0xb56d8658>

  File "/home/pi/services/ardupilot_manager/firmware/FirmwareDownload.py", line 85, in _manifest_is_valid
    return "format-version" in self._manifest or self.download_manifest()
                               │    │            │    └ <function FirmwareDownloader.download_manifest at 0xb5977898>
                               │    │            └ <firmware.FirmwareDownload.FirmwareDownloader object at 0xb56d8658>
                               │    └ {}
                               └ <firmware.FirmwareDownload.FirmwareDownloader object at 0xb56d8658>

  File "/home/pi/services/ardupilot_manager/firmware/FirmwareDownload.py", line 93, in download_manifest
    with urlopen(FirmwareDownloader._manifest_remote) as http_response:
         │       │                  └ 'https://firmware.ardupilot.org/manifest.json.gz'
         │       └ <class 'firmware.FirmwareDownload.FirmwareDownloader'>
         └ <function urlopen at 0xb5aebd60>

  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
           │      │    │    │     └ <object object at 0xb6b11288>
           │      │    │    └ None
           │      │    └ 'https://firmware.ardupilot.org/manifest.json.gz'
           │      └ <function OpenerDirector.open at 0xb5b0ada8>
           └ <urllib.request.OpenerDirector object at 0xb56304f0>
  File "/usr/local/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
               │    │     │    └ None
               │    │     └ <urllib.request.Request object at 0xb4de2af0>
               │    └ <function OpenerDirector._open at 0xb5b0adf0>
               └ <urllib.request.OpenerDirector object at 0xb56304f0>
  File "/usr/local/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             │    │           │    │            │         └ 'https'
             │    │           │    │            └ 'https'
             │    │           │    └ {'unknown': [<urllib.request.UnknownHandler object at 0xb4de2610>], 'http': [<urllib.request.HTTPHandler object at 0xb4de20b8...
             │    │           └ <urllib.request.OpenerDirector object at 0xb56304f0>
             │    └ <function OpenerDirector._call_chain at 0xb5b0ad60>
             └ <urllib.request.OpenerDirector object at 0xb56304f0>
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
             │     └ (<urllib.request.Request object at 0xb4de2af0>,)
             └ <bound method HTTPSHandler.https_open of <urllib.request.HTTPSHandler object at 0xb4de2298>>
  File "/usr/local/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           │    │       │    │      │                └ <urllib.request.Request object at 0xb4de2af0>
           │    │       │    │      └ <class 'http.client.HTTPSConnection'>
           │    │       │    └ <module 'urllib3.packages.six.moves.http_client' (<urllib3.packages.six._SixMetaPathImporter object at 0xb5bf73b8>)>
           │    │       └ <module 'http' from '/usr/local/lib/python3.9/http/__init__.py'>
           │    └ <function AbstractHTTPHandler.do_open at 0xb5b0ead8>
           └ <urllib.request.HTTPSHandler object at 0xb4de2298>
  File "/usr/local/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
          └ <class 'urllib.error.URLError'>

urllib.error.URLError: <urlopen error [SSL] unknown error (_ssl.c:1129)>
2022-08-12 22:58:51.822 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54494 - "GET /v1.0/available_firmwares?vehicle=Sub HTTP/1.0" 500
```

**Comment by patrickelectric** [comment]
@rafaellehmkuhl what is the status of this issue ?

**Comment by rafaellehmkuhl** [comment]
> @rafaellehmkuhl what is the status of this issue ?

Good question. I'm pretty sure it's unsolved.

**Comment by patrickelectric** [comment]
From our tests, it appears that we cant replicate it anymore.
