### ISSUE TITLE
[Kraken] -> NS_BINDING_ABORTED -> No Extensions available. Make sure the vehicle has internet access and try again. 

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#1642]
![image](https://user-images.githubusercontent.com/5920286/234032155-70b9fef2-bd8a-4b0f-aa0c-a8252e4cdab5.png)

**Comment by joaoantoniocardoso** [comment]
log:
```
2023-04-24 14:43:05.041 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56264 - "GET / HTTP/1.1" 200
2023-04-24 14:43:05.052 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56266 - "GET /register_service HTTP/1.1" 404
2023-04-24 14:43:05.061 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56268 - "GET /docs HTTP/1.1" 200
2023-04-24 14:43:05.071 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56270 - "GET /docs.json HTTP/1.1" 404
2023-04-24 14:43:05.081 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56272 - "GET /openapi.json HTTP/1.1" 200
2023-04-24 14:43:05.092 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56274 - "GET /v1.0/docs HTTP/1.1" 200
2023-04-24 14:43:05.102 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56276 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-04-24 14:43:05.112 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56278 - "GET / HTTP/1.1" 200
2023-04-24 14:43:05.121 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56280 - "GET /swagger.json HTTP/1.1" 404
2023-04-24 14:43:17.810 | ERROR    | commonwealth.utils.apis:custom_route_handler:36 - Unhandled service exception.
2023-04-24 14:43:17.811 | ERROR    | commonwealth.utils.apis:custom_route_handler:37 - 
Traceback (most recent call last):

  File "/home/pi/services/kraken/main.py", line 179, in <module>
    loop.run_until_complete(server.serve())
    │    │                  │      └ <function Server.serve at 0xb5c7f610>
    │    │                  └ <uvicorn.server.Server object at 0xb568e178>
    │    └ <function BaseEventLoop.run_until_complete at 0xb63d5bf8>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0xb63d5bb0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0xb63d7970>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
    │      └ <function Handle._run at 0xb641f658>
    └ <Handle <TaskStepMethWrapper object at 0xb55835b0>()>
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0xb55835b0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0xb55835b0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0xb55835b0>()>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0xb5651100>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb55aa220>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0xb5651148>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb55aa220>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb55aa220>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0xb568e268>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb55aa220>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb55aa220>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
                 │    └ <uvicorn.middleware.message_logger.MessageLoggerMiddleware object at 0xb568e1c0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0xb568e268>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/middleware/message_logger.py", line 61, in __call__
    await self.app(scope, inner_receive, inner_send)
          │    │   │      │              └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb56c3190>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <fastapi.applications.FastAPI object at 0xb56e58f8>
          └ <uvicorn.middleware.message_logger.MessageLoggerMiddleware object at 0xb568e1c0>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb56c3190>
                           │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb56c3190>
          │    │                │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb56e5af0>
          └ <fastapi.applications.FastAPI object at 0xb56e58f8>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0xb57fe538>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0xb56e5ad8>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb56e5af0>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb57fe4f0>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0xb56e5a00>
          └ <starlette.exceptions.ExceptionMiddleware object at 0xb56e5ad8>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb57fe4f0>
          │     │      │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │     └ <function Mount.handle at 0xb5e78190>
          └ <starlette.routing.Mount object at 0xb56864a8>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb57fe4f0>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <fastapi.applications.FastAPI object at 0xb5686490>
          └ <starlette.routing.Mount object at 0xb56864a8>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb57fe4f0>
                           │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb57fe4f0>
          │    │                │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb56865b0>
          └ <fastapi.applications.FastAPI object at 0xb5686490>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0xb56b3d18>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0xb5686598>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb56865b0>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb57ae928>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0xb56864d8>
          └ <starlette.exceptions.ExceptionMiddleware object at 0xb5686598>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb57ae928>
          │     │      │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │     └ <function Route.handle at 0xb5e67e38>
          └ <commonwealth.utils.apis.GenericErrorHandlingRoute object at 0xb56e5bf8>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb57ae928>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb56c3b68>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 9134), 'cl...
          │    └ <function request_response.<locals>.app at 0xb567a0b8>
          └ <commonwealth.utils.apis.GenericErrorHandlingRoute object at 0xb56e5bf8>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0xb55aac40>
                     └ <function GenericErrorHandlingRoute.get_route_handler.<locals>.custom_route_handler at 0xb567a070>
> File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/utils/apis.py", line 31, in custom_route_handler
    return await original_route_handler(request)
                 │                      └ <starlette.requests.Request object at 0xb55aac40>
                 └ <function get_request_handler.<locals>.app at 0xb5668fa0>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0xb5e78850>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {}
                 │         └ <function fetch_manifest at 0xb567a028>
                 └ <fastapi.dependencies.models.Dependant object at 0xb56e5d18>

  File "/home/pi/services/kraken/main.py", line 55, in fetch_manifest
    return await kraken.fetch_manifest()
                 │      └ <function Kraken.fetch_manifest at 0xb56686a0>
                 └ <kraken.Kraken object at 0xb56e5640>

  File "/home/pi/services/kraken/kraken.py", line 82, in fetch_manifest
    async with session.get(REPO_URL) as resp:
               │       │   └ 'https://bluerobotics.github.io/BlueOS-Extensions-Repository/manifest.json'
               │       └ <function ClientSession.get at 0xb5845cd0>
               └ <aiohttp.client.ClientSession object at 0xb55aaaf0>

  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
    │    │             │    └ <member '_coro' of '_BaseRequestContextManager' objects>
    │    │             └ <aiohttp.client._RequestContextManager object at 0xb5622b68>
    │    └ <member '_resp' of '_BaseRequestContextManager' objects>
    └ <aiohttp.client._RequestContextManager object at 0xb5622b68>
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
          │       └ <class 'asyncio.exceptions.TimeoutError'>
          └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>

asyncio.exceptions.TimeoutError
2023-04-24 14:43:25.691 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56496 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:43:25.712 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56546 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:43:55.762 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56796 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:43:55.780 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56852 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:44:08.211 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57178 - "GET / HTTP/1.1" 200
2023-04-24 14:44:08.223 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57180 - "GET /register_service HTTP/1.1" 404
2023-04-24 14:44:08.233 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57182 - "GET /docs HTTP/1.1" 200
2023-04-24 14:44:08.244 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57184 - "GET /docs.json HTTP/1.1" 404
2023-04-24 14:44:08.255 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57186 - "GET /openapi.json HTTP/1.1" 200
2023-04-24 14:44:08.266 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57188 - "GET /v1.0/docs HTTP/1.1" 200
2023-04-24 14:44:08.286 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57190 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-04-24 14:44:08.300 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57192 - "GET / HTTP/1.1" 200
2023-04-24 14:44:08.315 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57200 - "GET /swagger.json HTTP/1.1" 404
2023-04-24 14:44:25.988 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57512 - "GET /v1.0/installed_extensions HTTP/1.0" 200
2023-04-24 14:44:31.856 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57468 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:44:31.893 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57610 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:44:35.682 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57682 - "GET /v1.0/installed_extensions HTTP/1.0" 200
2023-04-24 14:44:40.755 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57684 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:44:40.788 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57806 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:45:09.379 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58288 - "GET / HTTP/1.1" 200
2023-04-24 14:45:09.389 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58290 - "GET /register_service HTTP/1.1" 404
2023-04-24 14:45:09.398 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58292 - "GET /docs HTTP/1.1" 200
2023-04-24 14:45:09.408 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58294 - "GET /docs.json HTTP/1.1" 404
2023-04-24 14:45:09.419 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58296 - "GET /openapi.json HTTP/1.1" 200
2023-04-24 14:45:09.429 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58298 - "GET /v1.0/docs HTTP/1.1" 200
2023-04-24 14:45:09.440 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58300 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-04-24 14:45:09.450 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58302 - "GET / HTTP/1.1" 200
2023-04-24 14:45:09.460 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58304 - "GET /swagger.json HTTP/1.1" 404
2023-04-24 14:45:10.957 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58032 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:45:10.987 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58404 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:45:42.950 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58770 - "GET /v1.0/installed_extensions HTTP/1.0" 200
2023-04-24 14:45:48.219 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58704 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:45:48.248 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58850 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:46:18.987 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59204 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:46:19.015 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59272 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:46:19.620 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59388 - "GET / HTTP/1.1" 200
2023-04-24 14:46:19.631 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59390 - "GET /register_service HTTP/1.1" 404
2023-04-24 14:46:19.641 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59392 - "GET /docs HTTP/1.1" 200
2023-04-24 14:46:19.650 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59394 - "GET /docs.json HTTP/1.1" 404
2023-04-24 14:46:19.660 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59396 - "GET /openapi.json HTTP/1.1" 200
2023-04-24 14:46:19.670 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59398 - "GET /v1.0/docs HTTP/1.1" 200
2023-04-24 14:46:19.680 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59400 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-04-24 14:46:19.690 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59402 - "GET / HTTP/1.1" 200
2023-04-24 14:46:19.699 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59404 - "GET /swagger.json HTTP/1.1" 404
2023-04-24 14:46:50.310 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59746 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:46:50.334 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59798 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:47:21.367 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60242 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:47:21.439 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60324 - "GET /v1.0/list_containers HTTP/1.0" 200
2023-04-24 14:47:25.195 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60500 - "GET / HTTP/1.1" 200
2023-04-24 14:47:25.209 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60502 - "GET /register_service HTTP/1.1" 404
2023-04-24 14:47:25.224 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60504 - "GET /docs HTTP/1.1" 200
2023-04-24 14:47:25.237 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60506 - "GET /docs.json HTTP/1.1" 404
2023-04-24 14:47:25.248 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60508 - "GET /openapi.json HTTP/1.1" 200
2023-04-24 14:47:25.261 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60510 - "GET /v1.0/docs HTTP/1.1" 200
2023-04-24 14:47:25.272 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60512 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-04-24 14:47:25.283 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60514 - "GET / HTTP/1.1" 200
2023-04-24 14:47:25.292 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60516 - "GET /swagger.json HTTP/1.1" 404
2023-04-24 14:47:51.543 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60872 - "GET /v1.0/stats HTTP/1.0" 200
2023-04-24 14:47:51.573 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60932 - "GET /v1.0/list_containers HTTP/1.0" 200

```

**Comment by joaoantoniocardoso** [comment]
After manually resetting the service:

![image](https://user-images.githubusercontent.com/5920286/234033564-47b9cb4b-4425-4c02-9a7c-d74801b94883.png)

**Comment by Williangalvani** [comment]
The timeout makes me believe this was a networking issue. is it easily replicated?

**Comment by joaoantoniocardoso** [comment]
> The timeout makes me believe this was a networking issue. is it easily replicated?

Not _easy_, BlueOS restart and container restart don't cause it, but it has been annoyingly happening just when I need to manage an extension -- pretty sure the chances are higher if I'm in a rush :laughing:

**Comment by joaoantoniocardoso** [comment]
I haven't seen this since then, so it's probably already fixed.
