### ISSUE TITLE
bug: ArduPilot dies in less than 24 hours

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#1831]
### Bug description

ArduPilot is dying after hours of executing, it appears to happen before 24 hours.
Confirmed happening here and with @rafaellehmkuhl.
The issue appears to happen only in beta.23, where the first occurrence shows in 1ad2b4e1c9152df309a427ae12637c989180b3ec.

### Steps to reproduce

1. Update to Beta.23.
2. Let it open for a full day.
3. The next day appears to be dead.

<details>
<summary>Log</summary>

```py
2023-06-27 18:24:24.428 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54800 - "GET / HTTP/1.1" 200
2023-06-27 18:24:24.462 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54802 - "GET /register_service HTTP/1.1" 404
2023-06-27 18:24:24.474 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54804 - "GET /docs HTTP/1.1" 200
2023-06-27 18:24:24.487 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54806 - "GET /docs.json HTTP/1.1" 404
2023-06-27 18:24:24.498 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54808 - "GET /openapi.json HTTP/1.1" 200
2023-06-27 18:24:24.514 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54810 - "GET /v1.0/docs HTTP/1.1" 200
2023-06-27 18:24:24.527 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54812 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-06-27 18:24:24.542 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:54814 - "GET /swagger.json HTTP/1.1" 404
2023-06-27 18:25:34.406 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55874 - "GET / HTTP/1.1" 200
2023-06-27 18:25:34.444 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55876 - "GET /register_service HTTP/1.1" 404
2023-06-27 18:25:34.457 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55878 - "GET /docs HTTP/1.1" 200
2023-06-27 18:25:34.472 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55880 - "GET /docs.json HTTP/1.1" 404
2023-06-27 18:25:34.484 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55882 - "GET /openapi.json HTTP/1.1" 200
2023-06-27 18:25:34.496 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55884 - "GET /v1.0/docs HTTP/1.1" 200
2023-06-27 18:25:34.513 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55886 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-06-27 18:25:34.529 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55888 - "GET /swagger.json HTTP/1.1" 404
2023-06-27 18:26:44.430 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56902 - "GET / HTTP/1.1" 200
2023-06-27 18:26:44.464 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56904 - "GET /register_service HTTP/1.1" 404
2023-06-27 18:26:44.475 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56906 - "GET /docs HTTP/1.1" 200
2023-06-27 18:26:44.488 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56908 - "GET /docs.json HTTP/1.1" 404
2023-06-27 18:26:44.503 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56910 - "GET /openapi.json HTTP/1.1" 200
2023-06-27 18:26:44.515 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56912 - "GET /v1.0/docs HTTP/1.1" 200
2023-06-27 18:26:44.527 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56914 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-06-27 18:26:44.540 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:56916 - "GET /swagger.json HTTP/1.1" 404
2023-06-27 18:27:59.309 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:57994 - "GET / HTTP/1.1" 200
2023-06-27 18:27:59.375 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58002 - "GET /register_service HTTP/1.1" 404
2023-06-27 18:27:59.388 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58004 - "GET /docs HTTP/1.1" 200
2023-06-27 18:27:59.402 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58006 - "GET /docs.json HTTP/1.1" 404
2023-06-27 18:27:59.414 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58008 - "GET /openapi.json HTTP/1.1" 200
2023-06-27 18:27:59.425 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58010 - "GET /v1.0/docs HTTP/1.1" 200
2023-06-27 18:27:59.437 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58012 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-06-27 18:27:59.451 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:58014 - "GET /swagger.json HTTP/1.1" 404
2023-06-27 18:29:04.077 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59012 - "GET / HTTP/1.1" 200
2023-06-27 18:29:04.110 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59014 - "GET /register_service HTTP/1.1" 404
2023-06-27 18:29:04.122 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59016 - "GET /docs HTTP/1.1" 200
2023-06-27 18:29:04.141 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59018 - "GET /docs.json HTTP/1.1" 404
2023-06-27 18:29:04.154 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59020 - "GET /openapi.json HTTP/1.1" 200
2023-06-27 18:29:04.166 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59022 - "GET /v1.0/docs HTTP/1.1" 200
2023-06-27 18:29:04.178 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59024 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-06-27 18:29:04.194 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:59026 - "GET /swagger.json HTTP/1.1" 404
2023-06-27 18:30:14.102 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60048 - "GET / HTTP/1.1" 200
2023-06-27 18:30:14.135 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60050 - "GET /register_service HTTP/1.1" 404
2023-06-27 18:30:14.146 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60052 - "GET /docs HTTP/1.1" 200
2023-06-27 18:30:14.160 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60054 - "GET /docs.json HTTP/1.1" 404
2023-06-27 18:30:14.172 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60056 - "GET /openapi.json HTTP/1.1" 200
2023-06-27 18:30:14.183 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60058 - "GET /v1.0/docs HTTP/1.1" 200
2023-06-27 18:30:14.200 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60060 - "GET /v1.0/openapi.json HTTP/1.1" 200
2023-06-27 18:30:14.215 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:60062 - "GET /swagger.json HTTP/1.1" 404
2023-06-27 18:31:15.878 | WARNING  | commonwealth.mavlink_comm.MavlinkComm:get_updated_mavlink_message:123 - no new messages after 5.0 seconds, triggering system-id detection
2023-06-27 18:31:15.900 | DEBUG    | commonwealth.mavlink_comm.MavlinkComm:get_most_recent_vehicle_id:102 - 1 (detected)
2023-06-27 18:31:15.902 | INFO     | commonwealth.mavlink_comm.MavlinkComm:set_system_id:28 - system_id set to: 1
2023-06-27 18:31:15.903 | ERROR    | commonwealth.utils.apis:custom_route_handler:36 - Unhandled service exception.
2023-06-27 18:31:15.905 | ERROR    | commonwealth.utils.apis:custom_route_handler:37 - Did not receive an updated HEARTBEAT before timeout.
Traceback (most recent call last):

  File "/home/pi/services/ardupilot_manager/main.py", line 253, in <module>
    loop.run_until_complete(server.serve())
    │    │                  │      └ <function Server.serve at 0xb5c9e220>
    │    │                  └ <uvicorn.server.Server object at 0xb54a4898>
    │    └ <function BaseEventLoop.run_until_complete at 0xb63eddf0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0xb63edda8>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0xb63efb68>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
    │      └ <function Handle._run at 0xb6434850>
    └ <Handle <TaskStepMethWrapper object at 0xb5830e50>()>
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0xb5830e50>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0xb5830e50>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0xb5830e50>()>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0xb5464b20>
                   │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb0988298>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0xb5464b68>
                   │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb0988298>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
                   │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb0988298>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0xb5447ee0>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb0988298>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb0988298>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <uvicorn.middleware.message_logger.MessageLoggerMiddleware object at 0xb54a4928>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0xb5447ee0>
  File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/middleware/message_logger.py", line 61, in __call__
    await self.app(scope, inner_receive, inner_send)
          │    │   │      │              └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb492ba90>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.applications.FastAPI object at 0xb5575ca0>
          └ <uvicorn.middleware.message_logger.MessageLoggerMiddleware object at 0xb54a4928>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb492ba90>
                           │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb492ba90>
          │    │                │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb54c30d0>
          └ <fastapi.applications.FastAPI object at 0xb5575ca0>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0xb492bec8>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0xb54c30b8>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb54c30d0>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb3ea8a48>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0xb5575d48>
          └ <starlette.exceptions.ExceptionMiddleware object at 0xb54c30b8>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb3ea8a48>
          │     │      │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Mount.handle at 0xb5e89a90>
          └ <starlette.routing.Mount object at 0xb549acd0>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb3ea8a48>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.applications.FastAPI object at 0xb549ac88>
          └ <starlette.routing.Mount object at 0xb549acd0>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb3ea8a48>
                           │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb3ea8a48>
          │    │                │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb549ab38>
          └ <fastapi.applications.FastAPI object at 0xb549ac88>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0xb3ea8b20>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0xb549ab50>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb549ab38>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb3ea8a90>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0xb549ad48>
          └ <starlette.exceptions.ExceptionMiddleware object at 0xb549ab50>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb3ea8a90>
          │     │      │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0xb5e89778>
          └ <commonwealth.utils.apis.GenericErrorHandlingRoute object at 0xb54c9a00>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb3ea8a90>
          │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb492bad8>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0xb5483580>
          └ <commonwealth.utils.apis.GenericErrorHandlingRoute object at 0xb54c9a00>
  File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0xb09883a0>
                     └ <function GenericErrorHandlingRoute.get_route_handler.<locals>.custom_route_handler at 0xb5483538>
> File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/utils/apis.py", line 31, in custom_route_handler
    return await original_route_handler(request)
                 │                      └ <starlette.requests.Request object at 0xb09883a0>
                 └ <function get_request_handler.<locals>.app at 0xb5483460>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0xb5e8b190>
  File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {}
                 │         └ <function get_vehicle_type at 0xb5483418>
                 └ <fastapi.dependencies.models.Dependant object at 0xb54c9b68>

  File "/home/pi/services/ardupilot_manager/main.py", line 124, in get_vehicle_type
    return await autopilot.vehicle_manager.get_vehicle_type()
                 │         │               └ <function VehicleManager.get_vehicle_type at 0xb572bf10>
                 │         └ <commonwealth.mavlink_comm.VehicleManager.VehicleManager object at 0xb54b9d00>
                 └ <ArduPilotManager.ArduPilotManager object at 0xb54b9220>

  File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/mavlink_comm/VehicleManager.py", line 75, in get_vehicle_type
    heartbeat_message = await self.mavlink2rest.get_updated_mavlink_message("HEARTBEAT")
                              │    │            └ <function MavlinkMessenger.get_updated_mavlink_message at 0xb572bcd0>
                              │    └ <commonwealth.mavlink_comm.MavlinkComm.MavlinkMessenger object at 0xb54b9dd8>
                              └ <commonwealth.mavlink_comm.VehicleManager.VehicleManager object at 0xb54b9d00>
  File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/mavlink_comm/MavlinkComm.py", line 125, in get_updated_mavlink_message
    raise FetchUpdatedMessageFail(f"Did not receive an updated {message_name} before timeout.")
          └ <class 'commonwealth.mavlink_comm.exceptions.FetchUpdatedMessageFail'>

commonwealth.mavlink_comm.exceptions.FetchUpdatedMessageFail: Did not receive an updated HEARTBEAT before timeout.
```
</details>

### Primary pain point(s)

ArduPilot should not die, or at least should be restarted.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
not replicable anymore
