### ISSUE TITLE
[ping]: exception=IndexError('list index out of range')

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#1924]
```bash 
2022-01-28 01:25:32.842 | INFO     | __main__:<module>:32 - Starting Ping Service.
2022-01-28 01:25:32.870 | DEBUG    | asyncio.selector_events:__init__:54 - Using selector: EpollSelector
2022-01-28 01:25:32.872 | INFO     | portwatcher:__init__:24 - PortWatcher Started
2022-01-28 01:25:32.889 | DEBUG    | portwatcher:start_watching:95 - Currently detected ports: ['usb:ttyACM0', 'amba:ttyAMA3', 'amba:ttyAMA2', 'amba:ttyAMA1', 'amba:ttyAMA0']
2022-01-28 01:25:32.890 | INFO     | portwatcher:probe_port:50 - Probing port: USB VID:PID=1209:5741 SER=1F0021001851353330343737 LOCATION=1-1.1:1.0
2022-01-28 01:25:32.892 | INFO     | pingprober:probe:17 - Probing /dev/ttyACM0 - Pixhawk1
2022-01-28 01:25:32.915 | INFO     | pingprober:detect_device:68 - An exception has occurred while attempting totalk Ping to device USB VID:PID=1209:5741 SER=1F0021001851353330343737 LOCATION=1-1.1:1.0: Failed to open the given serial port: (32, 'Broken pipe')If this is not a Ping device, this is expected.
2022-01-28 01:25:32.920 | INFO     | portwatcher:probe_port:50 - Probing port: fe201a00.serial
2022-01-28 01:25:32.921 | INFO     | pingprober:probe:17 - Probing /dev/ttyAMA3 - ttyAMA3
2022-01-28 01:25:33.546 | INFO     | portwatcher:probe_port:50 - Probing port: fe201800.serial
2022-01-28 01:25:33.547 | INFO     | pingprober:probe:17 - Probing /dev/ttyAMA2 - ttyAMA2
2022-01-28 01:25:34.164 | INFO     | portwatcher:probe_port:50 - Probing port: fe201600.serial
2022-01-28 01:25:34.165 | INFO     | pingprober:probe:17 - Probing /dev/ttyAMA1 - ttyAMA1
2022-01-28 01:25:34.785 | INFO     | portwatcher:probe_port:50 - Probing port: fe201000.serial
2022-01-28 01:25:34.786 | INFO     | pingprober:probe:17 - Probing /dev/ttyAMA0 - ttyAMA0
2022-01-28 01:25:35.915 | INFO     | pingprober:detect_device:68 - An exception has occurred while attempting totalk Ping to device fe201000.serial: Failed to open the given serial port: Write timeoutIf this is not a Ping device, this is expected.
2022-01-28 01:25:36.046 | INFO     | uvicorn.server:serve:64 - Started server process [224]
2022-01-28 01:25:36.048 | INFO     | uvicorn.lifespan.on:startup:26 - Waiting for application startup.
2022-01-28 01:25:36.051 | INFO     | uvicorn.lifespan.on:startup:38 - Application startup complete.
2022-01-28 01:25:36.054 | INFO     | uvicorn.server:_log_started_message:199 - Uvicorn running on http://0.0.0.0:9110 (Press CTRL+C to quit)
2022-01-28 01:25:37.121 | DEBUG    | ping360_ethernet_prober:find_ping360_ethernet:68 - timed out waiting for ping360 at ip 172.18.0.1
2022-01-28 01:25:38.124 | ERROR    | asyncio.base_events:default_exception_handler:1753 - Task exception was never retrieved
future: <Task finished name='Task-1' coro=<sensor_manager() done, defined at /home/pi/services/ping/main.py:69> exception=IndexError('list index out of range')>
Traceback (most recent call last):

> File "/home/pi/services/ping/main.py", line 76, in sensor_manager
    await port_watcher.start_watching()
          │            └ <function PortWatcher.start_watching at 0xb5663bf8>
          └ <portwatcher.PortWatcher object at 0xb5674ac0>

  File "/home/pi/services/ping/portwatcher.py", line 108, in start_watching
    await self.add_ping360()
          │    └ <function PortWatcher.add_ping360 at 0xb5663b68>
          └ <portwatcher.PortWatcher object at 0xb5674ac0>

  File "/home/pi/services/ping/portwatcher.py", line 64, in add_ping360
    ips_list = await find_ping360_ethernet()
                     └ <function find_ping360_ethernet at 0xb5663e80>

  File "/home/pi/services/ping/ping360_ethernet_prober.py", line 65, in find_ping360_ethernet
    raw_ip = decoded_message.split("IP Address:- ")[1].strip()
             │               └ <method 'split' of 'str' objects>
             └ 'OmniScan OS450\r\nCerulean Sonar\r\nMAC Address:-00-80-E1-26-07-29\r\nIP Address:-192.168.2.93\r\nPort:-51200\r\nFirmware Ve...

IndexError: list index out of range
2022-01-28 01:25:44.165 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:47024 - "GET / HTTP/1.1" 200
```

There was no Ping device connected, is this expected?

**Comment by Williangalvani** [comment]
no. it looks like we are not handling an exception properly there
